# Generated by Django 2.0.4 on 2018-04-19 17:04

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, default='', max_length=20, unique=True)),
                ('password', models.CharField(default='', max_length=100)),
                ('avatar', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(default='', max_length=20, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('about_me', models.TextField(default='hello', max_length=20)),
                ('last_seen', models.DateTimeField(default='2018-03-20 23:36:40')),
                ('followers', models.ManyToManyField(related_name='followeds', to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(default='')),
                ('comment_time', models.DateTimeField(default='2018-03-20 23:36:40')),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(default='')),
                ('post_time', models.DateTimeField(default='2018-03-20 23:36:40')),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='user.Post'),
        ),
        migrations.AddField(
            model_name='user',
            name='thumb_up_posts',
            field=models.ManyToManyField(related_name='thumbupeds', to='user.Post'),
        ),
        migrations.AddField(
            model_name='user',
            name='thumb_up_users',
            field=models.ManyToManyField(related_name='thumbupeds', to=settings.AUTH_USER_MODEL),
        ),
    ]
