# Generated by Django 2.0.1 on 2018-03-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, default='', max_length=20, unique=True)),
                ('password', models.CharField(default='', max_length=20)),
                ('avatar', models.FileField(default='', upload_to='uploads/')),
                ('email', models.CharField(default='hello', max_length=20, unique=True)),
                ('about_me', models.TextField(default='hello', max_length=20)),
                ('last_seen', models.DateTimeField(default='2018-03-20 23:36:40')),
                ('posts_num', models.IntegerField(default='')),
                ('follower_num', models.IntegerField(default=0)),
                ('followed_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
