# Generated by Django 2.0.1 on 2018-03-22 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180320_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bady', models.TextField(default='')),
                ('post_time', models.DateTimeField(default='2018-03-20 23:36:40')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='followed_num',
        ),
        migrations.RemoveField(
            model_name='user',
            name='follower_num',
        ),
        migrations.RemoveField(
            model_name='user',
            name='posts_num',
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='followeds', to='user.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='posts',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='author', to='user.Post'),
        ),
    ]
