# Generated by Django 2.0.1 on 2018-03-22 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180322_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='bady',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='user',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='user.User'),
        ),
    ]
