# Generated by Django 2.0.1 on 2018-03-22 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180322_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=20, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
