# Generated by Django 2.0.1 on 2018-04-03 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180322_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(default='')),
                ('comment_time', models.DateTimeField(default='2018-03-20 23:36:40')),
                ('post', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='user.Post')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='thumb_up_posts',
            field=models.ManyToManyField(related_name='thumbupeds', to='user.Post'),
        ),
        migrations.AddField(
            model_name='user',
            name='thumb_up_users',
            field=models.ManyToManyField(related_name='thumbupeds', to='user.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
